### ISSUE TITLE
Installing `pangeo-forge-recipes`

### ISSUE THREAD

**Issue by rwegener2** [pangeo-forge/pangeo-forge-recipes#282] opened 2022-02-14 18:29 UTC
## Issue
Answer the question: How should users set up an environment to use Pangeo Forge?

(It's very possible that this whole issue is not necessary and I am just confused, but I thought I would post it to attempt to clarify the current state)

### Long term plan: `conda`
In the long term it sounds like the preferred method is that users will be able to `conda install pangeo-forge-recipes`. At the current moment this is not yet implemented.

### Pip
There is a version of `pangeo-forge-recipes` that can be pip installed, but for me that verison gives an error when I try to use `XarrrayZarrRecipe`. If the current pip install is broken and we don't plan to support pip long term I wonder if we should remove `pangeo-forge-recipes` from pypi.

#### Error
`from pangeo_forge_recipes.recipes import XarrayZarrRecipe` yields:
```
[ImportError: cannot import name 'BlockSizeError' from 'fsspec.implementations.http' 
(/Users/rwegener/.pyenv/versions/miniconda3-4.7.12/envs/pf_env/lib/python3.9/site-
packages/fsspec/implementations/http.py)]()
```

### Local Development Install
As I understand it the only way to install `pangeo-forge-recipes` right now is to clone the repo and then do a `pip install -e`. 

## Action
For Ocean Sciences we will be using binder, so the installation question is not directly relevant. Still, I think it would be nice to have a clear recommended method for installation and for that to be directly accessible in the documentation.

**Comment by rabernat** [comment] 2022-02-14 18:30
cc @martindurant for fsspec error

**Comment by rabernat** [comment] 2022-02-14 18:32
This is a duplicate of https://github.com/pangeo-forge/pangeo-forge-recipes/issues/273

**Comment by rabernat** [comment] 2022-02-14 18:43
0.7 is now released. Rachel can you try to pip install that and see if things are working.

Sorry for the friction. But thanks for helping to surface these issues! It's very useful!

**Comment by rwegener2** [comment] 2022-02-14 21:48
Lighting fast turn around @rabernat!

So I can pip install 0.7 (as a sidenote, I did have to `brew install hdf5 netcdf`, but after that it worked). I get a new error when using the package, though:
```
>>> from pangeo_forge_recipes.recipes import XarrayZarrRecipe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rwegener/repos/pangeo-forge-recipes/pangeo_forge_recipes/recipes/__init__.py", line 1, in <module>
    from .reference_hdf_zarr import HDFReferenceRecipe
  File "/Users/rwegener/repos/pangeo-forge-recipes/pangeo_forge_recipes/recipes/reference_hdf_zarr.py", line 12, in <module>
    from ..executors.base import Pipeline, Stage
  File "/Users/rwegener/repos/pangeo-forge-recipes/pangeo_forge_recipes/executors/__init__.py", line 1, in <module>
    from .python import FunctionPipelineExecutor, GeneratorPipelineExecutor
  File "/Users/rwegener/repos/pangeo-forge-recipes/pangeo_forge_recipes/executors/python.py", line 5, in <module>
    from .base import Pipeline, PipelineExecutor
  File "/Users/rwegener/repos/pangeo-forge-recipes/pangeo_forge_recipes/executors/base.py", line 7, in <module>
    from mypy_extensions import NamedArg
ModuleNotFoundError: No module named 'mypy_extensions'
```

**Comment by cisaacstern** [comment] 2022-02-15 19:20
> I did have to brew install hdf5 netcdf, but after that it worked

@rwegener2, I'm a bit puzzled by this. The installation sequence I describe in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/284#issuecomment-1040690555 seems to work fine without going outside pip for `netcdf` and `hdf5`. Just to clarify further, do you get some kind of error if you follow the steps I outlined in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/284#issuecomment-1040690555?

And if it wasn't obvious already, thank you _so much_ for diligently working through all of these friction points, so that our next cohort of users doesn't have to!

**Comment by TomAugspurger** [comment] 2022-02-15 20:26
Maybe this was already said, but @rwegener2 are you on a Mac with the newer M1 chip?

**Closed** 2022-02-15 23:06 UTC

**Comment by rwegener2** [comment] 2022-02-16 17:36
> Maybe this was already said, but @rwegener2 are you on a Mac with the newer M1 chip?

Not yet said!  I am not on a Mac with a newer chip.  It's a 2019 Intel i5 with a Monterrey OS.

> Just to clarify further, do you get some kind of error if you follow the steps I outlined in https://github.com/pangeo-forge/pangeo-forge-recipes/pull/284#issuecomment-1040690555?

When I `pip install pangeo-forge-recipes` the first time I did get an error that let me to `brew install hdf5 netcdf`. My (shallow) understanding is that those libraries are related to the underlying C so I'm not sure if it is the responsibility of `pangeo-forge-recipes` to make sure I had those. I don't have a copy of the error I got (but I could try to reproduce it if anyone wants me to). 

### Summary
As of #284 all the dependencies are properly listed. `pip install pangeo-forge-recipes` works but is incomplete.

To make an environment right now a user should:
```
conda create -n pangeo-forge-recipes
conda activate
pip install pangeo-forge-recipes
pip install mypy_extensions
```

**Comment by rabernat** [comment] 2022-02-16 17:44
I'm totally baffled why you need to manually install mypy_extensions. It's a hard dependency now

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/dd77bba689e1960ed7fb47a415d8b9505ccf1b56/setup.cfg#L41

**Comment by rwegener2** [comment] 2022-02-16 17:55
@rabernat I haven't done this before but wouldn't we have to re-release to pypi with the updated dependencies for the pip installation to know that `mypy_extensions` is required?

**Comment by rabernat** [comment] 2022-02-17 12:40
Yes, very good point. We would need a new release.

In the meantime, it is possible to install directly the github master branch as

```
pip install git+https://github.com/pangeo-forge/pangeo-forge-recipes.git
```
