### ISSUE TITLE
Proposed feature: Inject additional attrs in `StoreToZarr` stage

### ISSUE THREAD

**Issue by jbusecke** [pangeo-forge/pangeo-forge-recipes#559] opened 2023-08-08 16:24 UTC
As part of the [CMIP6 feedstock](https://github.com/leap-stc/cmip6-leap-feedstock) I would like to be able to add [additional attributes](https://github.com/leap-stc/cmip6-leap-feedstock/issues/11) to the baked dataset (e.g. the specific urls used for the recipe and a timestamp). 

I naively tried this within a [preprocessor stage](https://github.com/leap-stc/cmip6-leap-feedstock/blob/6ca6f4937f2cdd6408d1f8b403cd7815f8bf993a/feedstock/recipe.py#L38-L46) but then realized that this would probably have to be implemented at the level of the [schema](https://github.com/pangeo-forge/pangeo-forge-recipes/blob/b6a7c81cfdf96cd41f2c4729c5606ece61434f67/pangeo_forge_recipes/transforms.py#L394) within the `StoreToZarr` stage. 

I would suggest to implement something like this:
```python
...
| StoreToZarr(..., add_attrs={'some_name', 'some_value'})
```
which should then result in these values being attached as dataset attributes to the zarr store.

**Comment by cisaacstern** [comment] 2023-08-08 20:56
This makes sense, @jbusecke, and should be simple to add.

For context, here's some general execution context we used to add to the global dataset attrs. Perhaps we want to restore some version of this, as part of your proposed enhancement:

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/3b3c13c358259a9b01367c91951d28826b6c252e/pangeo_forge_recipes/recipes/base.py#L57-L63

https://github.com/pangeo-forge/pangeo-forge-recipes/blob/3b3c13c358259a9b01367c91951d28826b6c252e/pangeo_forge_recipes/recipes/xarray_zarr.py#L594-L595

I general, I think the idea of tagging dataset attrs added by Pangeo Forge (and not inherited from the data provider) as `pangeo-forge:{attribute}` or similar, makes sense to me.

**Comment by cisaacstern** [comment] 2023-08-09 16:54
> This is great! Ill work on that on top of the dynamic chunking branch?

I would suggest keeping development of these features in separate branches, which will make reviewing them much easier.

If you want both features available together for your own recipe development, you could merge them into a separate `dev` branch on your fork of `pangeo-forge-recipes`.

**Comment by cisaacstern** [comment] 2023-08-10 19:10
Sorry, to clarify, what I meant was maintain three branches:

- PR feature branch A
- PR feature branch B
- Personal fork branch C (merge of A + B), not a PR, but used for recipe development.

**Comment by jbusecke** [comment] 2023-08-11 13:28
Ahh gotcha. Will try that in the coming days.

**Comment by cisaacstern** [comment] 2023-08-25 19:06
Just realized this is a duplicate of #480, so closing, and lets continue discussion there.

**Closed by cisaacstern** 2023-08-25 19:06 UTC
